SRC: Source update      Basically, remove everything there was before and replace it with      the 22.1 release.      Note: there is Nothing AIX related in the code at this moment,      and this form the start of modern integration.

diff --git a/packages/redhat/cloud-init.spec.in b/packages/redhat/cloud-init.spec.in
--- a/packages/redhat/cloud-init.spec.in
+++ b/packages/redhat/cloud-init.spec.in
@@ -1,66 +1,81 @@
-## This is a cheetah template
-%{!?python_sitelib: %global python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")}
+## template: jinja
+%define use_systemd (0%{?fedora} && 0%{?fedora} >= 18) || (0%{?rhel} && 0%{?rhel} >= 7)
+
+%if %{use_systemd}
+%define init_system systemd
+%else
+%define init_system sysvinit
+%endif
 
 # See: http://www.zarb.org/~jasonc/macros.php
 # Or: http://fedoraproject.org/wiki/Packaging:ScriptletSnippets
 # Or: http://www.rpm.org/max-rpm/ch-rpm-inside.html
 
-#for $d in $defines
-%define ${d}
-#end for
-
 Name:           cloud-init
-Version:        ${version}
-Release:        ${release}${subrelease}%{?dist}
+Version:        {{rpm_upstream_version}}
+Release:        1{{subrelease}}%{?dist}
 Summary:        Cloud instance init scripts
 
 Group:          System Environment/Base
-License:        GPLv3
+License:        Dual-licesed GPLv3 or Apache 2.0
 URL:            http://launchpad.net/cloud-init
 
-Source0:        ${archive_name}
+Source0:        {{archive_name}}
 BuildArch:      noarch
 BuildRoot:      %{_tmppath}
 
-BuildRequires:        python-devel
-BuildRequires:        python-setuptools
-BuildRequires:        python-cheetah
+%if "%{?el6}" == "1"
+BuildRequires:  python-argparse
+%endif
+%if %{use_systemd}
+Requires:           systemd
+BuildRequires:      systemd
+Requires:           systemd-units
+BuildRequires:      systemd-units
+%else
+Requires:           initscripts >= 8.36
+Requires(postun):   initscripts
+Requires(post):     chkconfig
+Requires(preun):    chkconfig
+%endif
+
+{% for r in buildrequires %}
+BuildRequires:  {{r}}
+{% endfor %}
 
 # System util packages needed
-Requires:       shadow-utils
-Requires:       rsyslog
-Requires:       iproute
-Requires:       e2fsprogs
-Requires:       net-tools
-Requires:       procps
-Requires:       shadow-utils
-Requires:       sudo >= 1.7.2p2-3
+%ifarch %{?ix86} x86_64 ia64
+Requires:       dmidecode
+%endif
 
-# Install pypi 'dynamic' requirements
-#for $r in $requires
-Requires:       ${r}
-#end for
+# python2.6 needs argparse
+%if "%{?el6}" == "1"
+Requires:  python-argparse
+%endif
+
+
+# Install 'dynamic' runtime reqs from *requirements.txt and pkg-deps.json.
+# Install them as BuildRequires too as they're used for testing.
+{% for r in requires %}
+BuildRequires:  {{r}}
+Requires:       {{r}}
+{% endfor %}
 
 # Custom patches
-#set $size = 0
-#for $p in $patches
-Patch${size}: $p
-#set $size += 1
-#end for
+{% for p in patches %}
+Patch{{loop.index0}}: {{p}}
+{% endfor %}
 
-#if $sysvinit
+%if "%{init_system}" == "systemd"
+Requires(post):       systemd
+Requires(preun):      systemd
+Requires(postun):     systemd
+%else
 Requires(post):       chkconfig
 Requires(postun):     initscripts
 Requires(preun):      chkconfig
 Requires(preun):      initscripts
-#end if
-
-#if $systemd
-BuildRequires:  systemd-units
-Requires(post):   systemd-units
-Requires(postun): systemd-units
-Requires(preun):  systemd-units
-#end if
+%endif
 
 %description
 Cloud-init is a set of init scripts for cloud instances.  Cloud instances
@@ -68,56 +83,74 @@ need special scripts to run during initialization to retrieve and install
 ssh keys and to let the user run various scripts.
 
 %prep
-%setup -q -n %{name}-%{version}~${release}
+%setup -q -n {{source_name}}
 
 # Custom patches activation
-#set $size = 0
-#for $p in $patches
-%patch${size} -p1
-#set $size += 1
-#end for
+{% for p in patches %}
+%patch{{loop.index0}} -p1
+{% endfor %}
 
 %build
-%{__python} setup.py build
+%{__python3} setup.py build
 
 %install
-rm -rf \$RPM_BUILD_ROOT
-%{__python} setup.py install -O1 \
-            --skip-build --root \$RPM_BUILD_ROOT \
-            --init-system=${init_sys}
+
+%{__python3} setup.py install -O1 \
+            --skip-build --root $RPM_BUILD_ROOT \
+            --init-system=%{init_system}
 
 # Note that /etc/rsyslog.d didn't exist by default until F15.
 # el6 request: https://bugzilla.redhat.com/show_bug.cgi?id=740420
-mkdir -p \$RPM_BUILD_ROOT/%{_sysconfdir}/rsyslog.d
+mkdir -p $RPM_BUILD_ROOT/%{_sysconfdir}/rsyslog.d
 cp -p tools/21-cloudinit.conf \
-      \$RPM_BUILD_ROOT/%{_sysconfdir}/rsyslog.d/21-cloudinit.conf
+      $RPM_BUILD_ROOT/%{_sysconfdir}/rsyslog.d/21-cloudinit.conf
+
+# Remove the tests
+rm -rf $RPM_BUILD_ROOT%{python3_sitelib}/tests
+
+# Required dirs...
+mkdir -p $RPM_BUILD_ROOT/%{_sharedstatedir}/cloud
+mkdir -p $RPM_BUILD_ROOT/%{_libexecdir}/%{name}
+
+# patch in the full version to version.py
+version_pys=$(cd "$RPM_BUILD_ROOT" && find . -name version.py -type f)
+[ -n "$version_pys" ] ||
+   { echo "failed to find 'version.py' to patch with version." 1>&2; exit 1; }
+( cd "$RPM_BUILD_ROOT" &&
+  sed -i "s,@@PACKAGED_VERSION@@,%{version}-%{release}," $version_pys )
 
 %clean
-rm -rf \$RPM_BUILD_ROOT
+rm -rf $RPM_BUILD_ROOT
 
 %post
 
-#if $systemd
-if [ \$1 -eq 1 ]
+%if "%{init_system}" == "systemd"
+if [ $1 -eq 1 ]
 then
     /bin/systemctl enable cloud-config.service     >/dev/null 2>&1 || :
     /bin/systemctl enable cloud-final.service      >/dev/null 2>&1 || :
     /bin/systemctl enable cloud-init.service       >/dev/null 2>&1 || :
     /bin/systemctl enable cloud-init-local.service >/dev/null 2>&1 || :
 fi
-#end if
-
-#if $sysvinit
+%else
 /sbin/chkconfig --add %{_initrddir}/cloud-init-local
 /sbin/chkconfig --add %{_initrddir}/cloud-init
 /sbin/chkconfig --add %{_initrddir}/cloud-config
 /sbin/chkconfig --add %{_initrddir}/cloud-final
-#end if
+%endif
 
 %preun
 
-#if $sysvinit
-if [ \$1 -eq 0 ]
+%if "%{init_system}" == "systemd"
+if [ $1 -eq 0 ]
+then
+    /bin/systemctl --no-reload disable cloud-config.service >/dev/null 2>&1 || :
+    /bin/systemctl --no-reload disable cloud-final.service  >/dev/null 2>&1 || :
+    /bin/systemctl --no-reload disable cloud-init.service   >/dev/null 2>&1 || :
+    /bin/systemctl --no-reload disable cloud-init-local.service >/dev/null 2>&1 || :
+fi
+%else
+if [ $1 -eq 0 ]
 then
     /sbin/service cloud-init stop >/dev/null 2>&1 || :
     /sbin/chkconfig --del cloud-init || :
@@ -128,48 +161,38 @@ then
     /sbin/service cloud-final stop >/dev/null 2>&1 || :
     /sbin/chkconfig --del cloud-final || :
 fi
-#end if
-
-#if $systemd
-if [ \$1 -eq 0 ]
-then
-    /bin/systemctl --no-reload disable cloud-config.service >/dev/null 2>&1 || :
-    /bin/systemctl --no-reload disable cloud-final.service  >/dev/null 2>&1 || :
-    /bin/systemctl --no-reload disable cloud-init.service   >/dev/null 2>&1 || :
-    /bin/systemctl --no-reload disable cloud-init-local.service >/dev/null 2>&1 || :
-fi
-#end if
+%endif
 
 %postun
 
-#if $systemd
+%if "%{init_system}" == "systemd"
 /bin/systemctl daemon-reload >/dev/null 2>&1 || :
-#end if
+%endif
 
 %files
 
-#if $sysvinit
+/lib/udev/rules.d/66-azure-ephemeral.rules
+
+%if "%{init_system}" == "systemd"
+/usr/lib/systemd/system-generators/cloud-init-generator
+%{_sysconfdir}/systemd/system/sshd-keygen@.service.d/disable-sshd-keygen-if-cloud-init-active.conf
+%{_unitdir}/cloud-*
+%else
 %attr(0755, root, root) %{_initddir}/cloud-config
 %attr(0755, root, root) %{_initddir}/cloud-final
 %attr(0755, root, root) %{_initddir}/cloud-init-local
 %attr(0755, root, root) %{_initddir}/cloud-init
-#end if
+%endif
 
-#if $systemd
-%{_unitdir}/cloud-*
-#end if
+%{_sysconfdir}/NetworkManager/dispatcher.d/hook-network-manager
+%{_sysconfdir}/dhcp/dhclient-exit-hooks.d/hook-dhclient
 
 # Program binaries
 %{_bindir}/cloud-init*
-
-# There doesn't seem to be an agreed upon place for these
-# although it appears the standard says /usr/lib but rpmbuild
-# will try /usr/lib64 ??
-/usr/lib/%{name}/uncloud-init
-/usr/lib/%{name}/write-ssh-key-fingerprints
+%{_bindir}/cloud-id*
 
 # Docs
-%doc TODO LICENSE ChangeLog requirements.txt
+%doc LICENSE ChangeLog TODO.rst requirements.txt
 %doc %{_defaultdocdir}/cloud-init/*
 
 # Configs
@@ -180,11 +203,12 @@ fi
 %dir                    %{_sysconfdir}/cloud/templates
 %config(noreplace)      %{_sysconfdir}/cloud/templates/*
 %config(noreplace) %{_sysconfdir}/rsyslog.d/21-cloudinit.conf
-%config(noreplace) %{_sysconfdir}/sudoers.d/cloud-init
+
+# Bash completion script
+%{_datadir}/bash-completion/completions/cloud-init
+
+%{_libexecdir}/%{name}
+%dir %{_sharedstatedir}/cloud
 
 # Python code is here...
-%{python_sitelib}/*
-
-%changelog
-
-${changelog}
+%{python3_sitelib}/*
